from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from tests.support import init_basic_workspace, json_from_stdout, load_yaml, run_hive


class ContextCompileTests(unittest.TestCase):
    def test_context_compile_writes_generated_pack_and_manifest(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = init_basic_workspace(Path(temp_dir))

            result = run_hive(
                "context",
                "compile",
                "departments/engineering",
                "--workspace",
                str(workspace),
                "--json",
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            output = json_from_stdout(result)
            self.assertTrue(output["ok"], output)
            self.assertEqual(output["target"], "departments/engineering")

            pack_path = Path(output["pack"])
            manifest_path = Path(output["manifest"])
            self.assertEqual(
                pack_path.relative_to(workspace.resolve()),
                Path("memory/generated/context-packs/nodes/departments/engineering/PACK.md"),
            )
            self.assertEqual(
                manifest_path.relative_to(workspace.resolve()),
                Path("memory/generated/context-packs/nodes/departments/engineering/MANIFEST.yaml"),
            )
            self.assertTrue(pack_path.is_file())
            self.assertTrue(manifest_path.is_file())

            pack_text = pack_path.read_text(encoding="utf-8")
            self.assertIn("# Context Pack: departments/engineering", pack_text)
            self.assertIn("Generated by Hive Synapse", pack_text)
            self.assertIn("Demo Organization", pack_text)
            self.assertIn("Engineering", pack_text)
            self.assertIn("ctxinv_demo_001.yaml", pack_text)

            manifest = load_yaml(manifest_path)
            self.assertEqual(manifest["target"], "departments/engineering")
            self.assertEqual(manifest["version"], 1)
            self.assertGreater(manifest["estimated_tokens"], 0)
            self.assertEqual(manifest["validation"]["status"], "warning")
            self.assertIn("ctxinv_demo_001.yaml", manifest["validation"]["warnings"])


if __name__ == "__main__":
    unittest.main()
