from __future__ import annotations

from pathlib import Path
from typing import Any

from .frontmatter import read_markdown, write_markdown
from .fs import atomic_write_text
from .graph import MemoryGraph
from .ids import utc_now_iso
from .operations import OperationLog
from .paths import WorkspacePaths, target_to_path_fragment


MAX_SNIPPET_WORDS = 90


def _read_if_exists(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="ignore").strip()


def _node_memory_dir(paths: WorkspacePaths, node_id: str) -> Path:
    return paths.root / "memory" / "records" / "nodes" / target_to_path_fragment(node_id)


def _edge_memory_dir(paths: WorkspacePaths, edge_id: str) -> Path:
    return paths.root / "memory" / "records" / "edges" / target_to_path_fragment(edge_id)


def _snippet(text: str, *, max_words: int = MAX_SNIPPET_WORDS) -> str:
    words: list[str] = []
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("---"):
            continue
        if line.startswith("#"):
            line = line.lstrip("# ").strip()
        words.extend(line.split())
        if len(words) >= max_words:
            break
    if not words:
        return "No summary available."
    result = " ".join(words[:max_words])
    if len(words) > max_words:
        result += "…"
    return result


def _brief_or_current_node(paths: WorkspacePaths, node_id: str) -> tuple[str, Path]:
    memory_dir = _node_memory_dir(paths, node_id)
    for name in ["BRIEF.md", "CURRENT.md"]:
        path = memory_dir / name
        text = _read_if_exists(path)
        if text:
            return _snippet(text), path
    return "No current memory found.", memory_dir / "CURRENT.md"


def _brief_or_current_edge(paths: WorkspacePaths, edge_id: str) -> tuple[str, Path]:
    memory_dir = _edge_memory_dir(paths, edge_id)
    for name in ["BRIEF.md", "CURRENT.md"]:
        path = memory_dir / name
        text = _read_if_exists(path)
        if text:
            return _snippet(text), path
    return "No edge memory found.", memory_dir / "CURRENT.md"


def _append_previous_brief_to_history(brief_path: Path, history_path: Path, *, timestamp: str, actor: str) -> None:
    current_history = _read_if_exists(history_path) or f"# Brief History: {brief_path.parent.name}\n"
    if not brief_path.exists():
        atomic_write_text(history_path, current_history.rstrip() + f"\n\n## {timestamp} — created by {actor}\n\nInitial generated brief.\n")
        return
    existing = read_markdown(brief_path)
    old_body = existing.body.strip() or brief_path.read_text(encoding="utf-8", errors="ignore").strip()
    addition = f"\n\n## {timestamp} — superseded by {actor}\n\n{old_body}\n"
    atomic_write_text(history_path, current_history.rstrip() + addition)


def compact_node(root: Path, target: str, *, actor: str = "system:compact") -> dict[str, Any]:
    paths = WorkspacePaths(root.resolve())
    paths.require_workspace()
    graph = MemoryGraph(paths.root)
    node = graph.nodes.get(target)
    if node is None:
        raise ValueError(f"Node not found: {target}")
    now = utc_now_iso()
    memory_dir = _node_memory_dir(paths, target)
    brief_path = memory_dir / "BRIEF.md"
    history_path = memory_dir / "BRIEF_HISTORY.md"

    child_nodes = sorted(
        (child for child in graph.active_nodes().values() if target in child.parents),
        key=lambda child: child.id,
    )
    connected_edges = [graph.edges[edge_id] for edge_id in graph.connected_edges(target)]
    candidate_paths = sorted((memory_dir / "candidates").glob("*.md"))
    current_text = _read_if_exists(memory_dir / "CURRENT.md")
    charter_text = _read_if_exists(memory_dir / "CHARTER.md")

    body_parts = [
        f"# Brief: {node.title}",
        "This file is generated by Hive Synapse compaction. Hand-edit CURRENT.md or CHARTER.md, then re-run compaction.",
        "## Current Operating Summary",
        _snippet(current_text),
    ]
    if charter_text:
        body_parts.extend(["## Charter Signal", _snippet(charter_text)])
    body_parts.append("## Immediate Children")
    if child_nodes:
        for child in child_nodes:
            snippet, source = _brief_or_current_node(paths, child.id)
            body_parts.append(f"- `{child.id}` ({child.kind}, {child.status}): {snippet} [source: {source.relative_to(paths.root)}]")
    else:
        body_parts.append("- No active child nodes.")
    body_parts.append("## Shared Edge Context")
    if connected_edges:
        for edge in connected_edges:
            snippet, source = _brief_or_current_edge(paths, edge.id)
            other_nodes = ", ".join(node_id for node_id in edge.nodes if node_id != target)
            body_parts.append(f"- `{edge.id}` with {other_nodes}: {snippet} [source: {source.relative_to(paths.root)}]")
    else:
        body_parts.append("- No active shared edges.")
    body_parts.append("## Candidate Memory Backlog")
    if candidate_paths:
        for candidate_path in candidate_paths[:20]:
            doc = read_markdown(candidate_path)
            record_id = doc.frontmatter.get("id", candidate_path.stem)
            body_parts.append(f"- `{record_id}`: {_snippet(doc.body)}")
        if len(candidate_paths) > 20:
            body_parts.append(f"- {len(candidate_paths) - 20} additional candidates omitted from brief.")
    else:
        body_parts.append("- No candidate records awaiting review.")

    _append_previous_brief_to_history(brief_path, history_path, timestamp=now, actor=actor)
    frontmatter = {
        "id": f"brief_node_{target.replace('/', '_')}",
        "type": "brief",
        "scope": "node",
        "authority": "summary",
        "node": target,
        "created_at": now,
        "created_by": actor,
        "source_refs": [
            {"source_id": f"node:{target}:current", "locator": str((memory_dir / "CURRENT.md").relative_to(paths.root))},
            {"source_id": f"node:{target}:charter", "locator": str((memory_dir / "CHARTER.md").relative_to(paths.root))},
        ],
        "confidence": 0.8,
        "sensitivity": "internal",
        "status": "active",
        "tags": ["brief", "compaction", "generated"],
        "generated": True,
        "child_count": len(child_nodes),
        "edge_count": len(connected_edges),
        "candidate_count": len(candidate_paths),
    }
    write_markdown(brief_path, frontmatter, "\n\n".join(body_parts))
    op = OperationLog(paths).append(
        operation_type="node_compact",
        actor=actor,
        targets=[str(paths.root), target],
        command="hive node compact",
        changed_files=[{"path": str(brief_path.relative_to(paths.root))}, {"path": str(history_path.relative_to(paths.root))}],
        changed_records=[{"id": frontmatter["id"], "type": "brief", "node": target}],
        rollback={"supported": True, "strategy": "restore_from_git_or_BRIEF_HISTORY"},
    )
    return {
        "ok": True,
        "target": target,
        "brief": str(brief_path),
        "history": str(history_path),
        "operation": op.id,
        "child_count": len(child_nodes),
        "edge_count": len(connected_edges),
        "candidate_count": len(candidate_paths),
    }


def compact_edge(root: Path, edge_id: str, *, actor: str = "system:compact") -> dict[str, Any]:
    paths = WorkspacePaths(root.resolve())
    paths.require_workspace()
    graph = MemoryGraph(paths.root)
    edge = graph.edges.get(edge_id)
    if edge is None:
        raise ValueError(f"Edge not found: {edge_id}")
    now = utc_now_iso()
    memory_dir = _edge_memory_dir(paths, edge_id)
    brief_path = memory_dir / "BRIEF.md"
    history_path = memory_dir / "BRIEF_HISTORY.md"
    current_text = _read_if_exists(memory_dir / "CURRENT.md")

    body_parts = [
        f"# Edge Brief: {edge.title}",
        "This file is generated by Hive Synapse compaction. Hand-edit CURRENT.md, then re-run edge compaction.",
        "## Shared Operating Summary",
        _snippet(current_text),
        "## Participating Nodes",
    ]
    for node_id in edge.nodes:
        node = graph.nodes.get(node_id)
        snippet, source = _brief_or_current_node(paths, node_id)
        title = node.title if node else node_id
        kind = node.kind if node else "missing"
        body_parts.append(f"- `{node_id}` ({kind}, {title}): {snippet} [source: {source.relative_to(paths.root)}]")

    _append_previous_brief_to_history(brief_path, history_path, timestamp=now, actor=actor)
    frontmatter = {
        "id": f"brief_edge_{edge_id.replace('/', '_')}",
        "type": "edge_brief",
        "scope": "edge",
        "authority": "summary",
        "edge": edge_id,
        "created_at": now,
        "created_by": actor,
        "source_refs": [{"source_id": f"edge:{edge_id}:current", "locator": str((memory_dir / "CURRENT.md").relative_to(paths.root))}],
        "confidence": 0.8,
        "sensitivity": "internal",
        "status": "active",
        "tags": ["brief", "compaction", "generated", "edge"],
        "generated": True,
        "node_count": len(edge.nodes),
    }
    write_markdown(brief_path, frontmatter, "\n\n".join(body_parts))
    op = OperationLog(paths).append(
        operation_type="edge_compact",
        actor=actor,
        targets=[str(paths.root), edge_id, *edge.nodes],
        command="hive edge compact",
        changed_files=[{"path": str(brief_path.relative_to(paths.root))}, {"path": str(history_path.relative_to(paths.root))}],
        changed_records=[{"id": frontmatter["id"], "type": "edge_brief", "edge": edge_id}],
        rollback={"supported": True, "strategy": "restore_from_git_or_BRIEF_HISTORY"},
    )
    return {
        "ok": True,
        "edge": edge_id,
        "brief": str(brief_path),
        "history": str(history_path),
        "operation": op.id,
        "node_count": len(edge.nodes),
    }
