from __future__ import annotations

from pathlib import Path
from typing import Any

from . import simple_yaml as yaml
from .fs import atomic_write_text
from .graph import MemoryGraph
from .ids import new_id, utc_now_iso
from .models import ContextPackManifest
from .operations import OperationLog
from .paths import WorkspacePaths, target_to_path_fragment


def _read_if_exists(path: Path) -> str:
    if path.exists():
        return path.read_text(encoding="utf-8").strip()
    return ""


def _current_memory(paths: WorkspacePaths, target: str) -> tuple[str, Path]:
    path = paths.root / "memory" / "records" / "nodes" / target_to_path_fragment(target) / "CURRENT.md"
    return _read_if_exists(path), path


def _edge_memory(paths: WorkspacePaths, edge_id: str) -> tuple[str, Path]:
    path = paths.root / "memory" / "records" / "edges" / edge_id / "CURRENT.md"
    return _read_if_exists(path), path


def _load_budget(paths: WorkspacePaths) -> dict[str, Any]:
    budget_path = paths.root / "policies" / "context-budget.yaml"
    if not budget_path.exists():
        default = {
            "id": "context_budget_default",
            "budget_tokens": 24000,
            "warn_at_ratio": 0.8,
            "on_over_budget": "create_compaction_job",
        }
        atomic_write_text(budget_path, yaml.safe_dump(default, sort_keys=False))
        return default
    data = yaml.safe_load(budget_path.read_text(encoding="utf-8")) or {}
    return data if isinstance(data, dict) else {}


def compile_context_pack(root: Path, target: str) -> tuple[Path, Path]:
    paths = WorkspacePaths(root.resolve())
    paths.require_workspace()
    graph = MemoryGraph(paths.root)
    target_fragment = target_to_path_fragment(target)
    output_dir = paths.root / "memory" / "generated" / "context-packs" / "nodes" / target_fragment
    output_dir.mkdir(parents=True, exist_ok=True)

    sections: list[dict[str, Any]] = []
    body_parts = [
        f"# Context Pack: {target}",
        "## Runtime Protocol\n\nGenerated by Hive Synapse. Context packs are generated artifacts.",
    ]

    for parent in graph.parent_chain(target):
        text, path = _current_memory(paths, parent)
        body_parts.append(f"## Parent Context: {parent}\n\n{text or '_No current memory found._'}")
        sections.append({"name": f"parent:{parent}", "estimated_tokens": len(text.split()), "source": str(path.relative_to(paths.root))})

    target_text, target_path = _current_memory(paths, target)
    body_parts.append(f"## Target Context\n\n{target_text or '_No target current memory found._'}")
    sections.append({"name": "target", "estimated_tokens": len(target_text.split()), "source": str(target_path.relative_to(paths.root))})

    for edge_id in graph.connected_edges(target):
        text, path = _edge_memory(paths, edge_id)
        body_parts.append(f"## Shared Edge Context: {edge_id}\n\n{text or '_No edge current memory found._'}")
        sections.append({"name": f"edge:{edge_id}", "estimated_tokens": len(text.split()), "source": str(path.relative_to(paths.root))})

    dirty_dir = paths.root / "memory" / "state" / "context-dirty"
    dirty_warnings = [path.name for path in sorted(dirty_dir.glob("*.yaml")) if target in path.read_text(encoding="utf-8", errors="ignore")]
    body_parts.append(
        "## Dirty Context Warnings\n\n"
        + ("\n".join(f"- {item}" for item in dirty_warnings) if dirty_warnings else "None.")
    )

    pack = "\n\n".join(body_parts)
    pack_path = output_dir / "PACK.md"
    atomic_write_text(pack_path, pack + "\n")

    estimated_tokens = max(1, len(pack.split()))
    budget = _load_budget(paths)
    budget_tokens = int(budget.get("budget_tokens", 24000))
    validation = {"status": "warning" if dirty_warnings else "passed", "errors": [], "warnings": dirty_warnings}
    if estimated_tokens > budget_tokens:
        validation = {"status": "over_budget", "errors": [], "warnings": ["context_over_budget"]}
        job_id = new_id("job")
        job = {
            "id": job_id,
            "type": "node_compact",
            "target": target,
            "status": "pending",
            "reason": "Context pack exceeded token budget.",
            "created_at": utc_now_iso(),
            "inputs": {"estimated_tokens": estimated_tokens, "budget_tokens": budget_tokens},
        }
        atomic_write_text(paths.root / "memory" / "jobs" / "pending" / f"{job_id}.yaml", yaml.safe_dump(job, sort_keys=False))

    manifest = ContextPackManifest(
        id=f"context_pack_{target.replace('/', '_')}_001",
        target=target,
        version=1,
        compiled_at=utc_now_iso(),
        policy_id=str(budget.get("id", "default")),
        estimated_tokens=estimated_tokens,
        budget_tokens=budget_tokens,
        sections=[{"name": "protocol", "estimated_tokens": 12}, *sections],
        source_watermark=utc_now_iso(),
        validation=validation,
    )
    manifest_path = output_dir / "MANIFEST.yaml"
    atomic_write_text(manifest_path, yaml.safe_dump(manifest.model_dump(mode="json"), sort_keys=False))
    OperationLog(paths).append(
        operation_type="context_compile",
        actor="system:context",
        targets=[str(paths.root), target],
        command="hive context compile",
        changed_files=[
            {"path": str(pack_path.relative_to(paths.root))},
            {"path": str(manifest_path.relative_to(paths.root))},
        ],
        changed_records=[{"id": manifest.id, "type": "context_pack"}],
        rollback={"supported": False, "strategy": "regenerate_context_pack"},
    )
    return pack_path, manifest_path


def context_impact(root: Path, target: str) -> dict[str, Any]:
    paths = WorkspacePaths(root.resolve())
    paths.require_workspace()
    return {"ok": True, **MemoryGraph(paths.root).impact(target).as_dict()}


def invalidate_context(root: Path, target: str, *, reason: str, actor: str = "system:context") -> dict[str, Any]:
    paths = WorkspacePaths(root.resolve())
    paths.require_workspace()
    impact = MemoryGraph(paths.root).impact(target)
    invalidation_id = new_id("ctxinv")
    record = {
        "id": invalidation_id,
        "target": target,
        "reason": reason,
        "created_at": utc_now_iso(),
        "severity": "normal",
        "affected_context_packs": impact.context_packs,
        "affected_targets": impact.affected_targets,
        "status": "open",
    }
    path = paths.context_dirty / f"{invalidation_id}.yaml"
    atomic_write_text(path, yaml.safe_dump(record, sort_keys=False))
    operation = OperationLog(paths).append(
        operation_type="context_invalidate",
        actor=actor,
        targets=[str(paths.root), target, *impact.affected_targets],
        command="hive context invalidate",
        changed_files=[{"path": str(path.relative_to(paths.root))}],
        changed_records=[{"id": invalidation_id, "type": "context_invalidation"}],
        rollback={"supported": True, "strategy": "close_dirty_marker"},
    )
    return {"ok": True, "invalidation": record, "impact": impact.as_dict(), "operation": operation.id}
