from __future__ import annotations

from pathlib import Path

from . import simple_yaml as yaml

from .fs import atomic_write_text
from .ids import utc_now_iso
from .models import ContextPackManifest
from .paths import WorkspacePaths, target_to_path_fragment


def _read_if_exists(path: Path) -> str:
    if path.exists():
        return path.read_text(encoding="utf-8").strip()
    return ""


def compile_context_pack(root: Path, target: str) -> tuple[Path, Path]:
    paths = WorkspacePaths(root.resolve())
    target_fragment = target_to_path_fragment(target)
    output_dir = paths.root / "memory" / "generated" / "context-packs" / "nodes" / target_fragment
    output_dir.mkdir(parents=True, exist_ok=True)

    org_current = _read_if_exists(paths.root / "memory" / "records" / "nodes" / "org" / "CURRENT.md")
    target_current = _read_if_exists(paths.root / "memory" / "records" / "nodes" / target_fragment / "CURRENT.md")
    dirty_dir = paths.root / "memory" / "state" / "context-dirty"
    dirty_warnings = [path.name for path in dirty_dir.glob("*.yaml")]

    pack = "\n\n".join(
        [
            f"# Context Pack: {target}",
            "## Runtime Protocol\n\nGenerated by Hive Synapse. Context packs are generated artifacts.",
            f"## Organization Context\n\n{org_current or '_No organization current memory found._'}",
            f"## Target Context\n\n{target_current or '_No target current memory found._'}",
            "## Dirty Context Warnings\n\n"
            + ("\n".join(f"- {item}" for item in dirty_warnings) if dirty_warnings else "None."),
        ]
    )
    pack_path = output_dir / "PACK.md"
    atomic_write_text(pack_path, pack + "\n")

    estimated_tokens = max(1, len(pack.split()))
    manifest = ContextPackManifest(
        id=f"context_pack_{target.replace('/', '_')}_001",
        target=target,
        version=1,
        compiled_at=utc_now_iso(),
        policy_id="default",
        estimated_tokens=estimated_tokens,
        budget_tokens=24000,
        sections=[
            {"name": "protocol", "estimated_tokens": 12, "budget_tokens": 2500},
            {"name": "org", "estimated_tokens": len(org_current.split()), "budget_tokens": 2000},
            {"name": "node", "estimated_tokens": len(target_current.split()), "budget_tokens": 5000},
        ],
        source_watermark=utc_now_iso(),
        validation={"status": "warning" if dirty_warnings else "passed", "errors": [], "warnings": dirty_warnings},
    )
    manifest_path = output_dir / "MANIFEST.yaml"
    atomic_write_text(manifest_path, yaml.safe_dump(manifest.model_dump(mode="json"), sort_keys=False))
    return pack_path, manifest_path
