"""Context-pack compilation and invalidation.

Module guide:
- `compile_context_pack` builds generated `PACK.md` and `MANIFEST.yaml` files.
- `context_impact` reports descendants, edges, actors, and affected targets.
- `invalidate_context` writes or observes dirty-context markers per policy.

Maintenance: update this guide when adding public functions/classes to this module.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from . import simple_yaml as yaml
from .charters import charter_path
from .fs import atomic_write_text
from .graph import MemoryGraph
from .ids import new_id, utc_now_iso
from .models import ContextPackManifest
from .operations import OperationLog
from .paths import WorkspacePaths, target_to_path_fragment
from .policies import context_invalidation_decision, operation_policy


def _read_if_exists(path: Path) -> str:
    if path.exists():
        return path.read_text(encoding="utf-8").strip()
    return ""


def _charter_memory(paths: WorkspacePaths, target: str) -> tuple[str, Path]:
    path = charter_path(paths, target)
    return _read_if_exists(path), path


def _current_memory(paths: WorkspacePaths, target: str) -> tuple[str, Path]:
    path = (
        paths.root / "memory" / "records" / "nodes" / target_to_path_fragment(target) / "CURRENT.md"
    )
    return _read_if_exists(path), path


def _node_brief(paths: WorkspacePaths, target: str) -> tuple[str, Path]:
    path = (
        paths.root / "memory" / "records" / "nodes" / target_to_path_fragment(target) / "BRIEF.md"
    )
    return _read_if_exists(path), path


def _edge_memory(paths: WorkspacePaths, edge_id: str) -> tuple[str, Path]:
    path = (
        paths.root
        / "memory"
        / "records"
        / "edges"
        / target_to_path_fragment(edge_id)
        / "CURRENT.md"
    )
    return _read_if_exists(path), path


def _edge_brief(paths: WorkspacePaths, edge_id: str) -> tuple[str, Path]:
    path = (
        paths.root / "memory" / "records" / "edges" / target_to_path_fragment(edge_id) / "BRIEF.md"
    )
    return _read_if_exists(path), path


def _load_budget(paths: WorkspacePaths) -> dict[str, Any]:
    budget_path = paths.root / "policies" / "context-budget.yaml"
    if not budget_path.exists():
        default = {
            "id": "context_budget_default",
            "budget_tokens": 24000,
            "warn_at_ratio": 0.8,
            "on_over_budget": "create_compaction_job",
        }
        atomic_write_text(budget_path, yaml.safe_dump(default, sort_keys=False))
        return default
    data = yaml.safe_load(budget_path.read_text(encoding="utf-8")) or {}
    return data if isinstance(data, dict) else {}


def compile_context_pack(root: Path, target: str) -> tuple[Path, Path]:
    paths = WorkspacePaths(root.resolve())
    paths.require_workspace()
    graph = MemoryGraph(paths.root)
    target_fragment = target_to_path_fragment(target)
    output_dir = paths.root / "memory" / "generated" / "context-packs" / "nodes" / target_fragment
    output_dir.mkdir(parents=True, exist_ok=True)

    sections: list[dict[str, Any]] = []
    body_parts = [
        f"# Context Pack: {target}",
        "## Runtime Protocol\n\nGenerated by Hive Synapse. Context packs are generated artifacts.",
    ]

    for parent in graph.parent_chain(target):
        charter_text, charter_source = _charter_memory(paths, parent)
        if charter_text:
            body_parts.append(f"## Parent Charter: {parent}\n\n{charter_text}")
            sections.append(
                {
                    "name": f"parent_charter:{parent}",
                    "estimated_tokens": len(charter_text.split()),
                    "source": str(charter_source.relative_to(paths.root)),
                }
            )
        brief_text, brief_path = _node_brief(paths, parent)
        if brief_text:
            body_parts.append(f"## Parent Brief: {parent}\n\n{brief_text}")
            sections.append(
                {
                    "name": f"parent_brief:{parent}",
                    "estimated_tokens": len(brief_text.split()),
                    "source": str(brief_path.relative_to(paths.root)),
                }
            )
        text, path = _current_memory(paths, parent)
        body_parts.append(f"## Parent Context: {parent}\n\n{text or '_No current memory found._'}")
        sections.append(
            {
                "name": f"parent:{parent}",
                "estimated_tokens": len(text.split()),
                "source": str(path.relative_to(paths.root)),
            }
        )

    target_charter, target_charter_path = _charter_memory(paths, target)
    if target_charter:
        body_parts.append(f"## Target Charter\n\n{target_charter}")
        sections.append(
            {
                "name": "target_charter",
                "estimated_tokens": len(target_charter.split()),
                "source": str(target_charter_path.relative_to(paths.root)),
            }
        )

    target_brief, target_brief_path = _node_brief(paths, target)
    if target_brief:
        body_parts.append(f"## Target Brief\n\n{target_brief}")
        sections.append(
            {
                "name": "target_brief",
                "estimated_tokens": len(target_brief.split()),
                "source": str(target_brief_path.relative_to(paths.root)),
            }
        )

    target_text, target_path = _current_memory(paths, target)
    body_parts.append(f"## Target Context\n\n{target_text or '_No target current memory found._'}")
    sections.append(
        {
            "name": "target",
            "estimated_tokens": len(target_text.split()),
            "source": str(target_path.relative_to(paths.root)),
        }
    )

    for edge_id in graph.connected_edges(target):
        edge_brief, edge_brief_path = _edge_brief(paths, edge_id)
        if edge_brief:
            body_parts.append(f"## Shared Edge Brief: {edge_id}\n\n{edge_brief}")
            sections.append(
                {
                    "name": f"edge_brief:{edge_id}",
                    "estimated_tokens": len(edge_brief.split()),
                    "source": str(edge_brief_path.relative_to(paths.root)),
                }
            )
        text, path = _edge_memory(paths, edge_id)
        body_parts.append(
            f"## Shared Edge Context: {edge_id}\n\n{text or '_No edge current memory found._'}"
        )
        sections.append(
            {
                "name": f"edge:{edge_id}",
                "estimated_tokens": len(text.split()),
                "source": str(path.relative_to(paths.root)),
            }
        )

    dirty_dir = paths.root / "memory" / "state" / "context-dirty"
    dirty_warnings = [
        path.name
        for path in sorted(dirty_dir.glob("*.yaml"))
        if target in path.read_text(encoding="utf-8", errors="ignore")
    ]
    body_parts.append(
        "## Dirty Context Warnings\n\n"
        + ("\n".join(f"- {item}" for item in dirty_warnings) if dirty_warnings else "None.")
    )

    pack = "\n\n".join(body_parts)
    pack_path = output_dir / "PACK.md"
    atomic_write_text(pack_path, pack + "\n")

    estimated_tokens = max(1, len(pack.split()))
    budget = _load_budget(paths)
    compaction_policy = operation_policy(paths, "compaction", target=target)
    budget_tokens = int(budget.get("budget_tokens", 24000))
    on_over_budget = str(
        compaction_policy.get("on_over_budget")
        or budget.get("on_over_budget", "create_compaction_job")
    )
    compaction_mode = str(compaction_policy.get("mode", "threshold")).lower()
    validation = {
        "status": "warning" if dirty_warnings else "passed",
        "errors": [],
        "warnings": dirty_warnings,
    }
    if estimated_tokens > budget_tokens:
        validation = {"status": "over_budget", "errors": [], "warnings": ["context_over_budget"]}
        if (
            compaction_mode in {"threshold", "auto", "automatic"}
            and on_over_budget == "create_compaction_job"
        ):
            job_id = new_id("job")
            job = {
                "id": job_id,
                "type": "node_compact",
                "target": target,
                "status": "pending",
                "reason": "Context pack exceeded token budget.",
                "created_at": utc_now_iso(),
                "inputs": {"estimated_tokens": estimated_tokens, "budget_tokens": budget_tokens},
            }
            atomic_write_text(
                paths.root / "memory" / "jobs" / "pending" / f"{job_id}.yaml",
                yaml.safe_dump(job, sort_keys=False),
            )
            validation["warnings"].append("compaction_job_created")
        else:
            validation["warnings"].append(f"compaction_policy:{compaction_mode}")

    manifest = ContextPackManifest(
        id=f"context_pack_{target.replace('/', '_')}_001",
        target=target,
        version=1,
        compiled_at=utc_now_iso(),
        policy_id=str(budget.get("id", "default")),
        estimated_tokens=estimated_tokens,
        budget_tokens=budget_tokens,
        sections=[{"name": "protocol", "estimated_tokens": 12}, *sections],
        source_watermark=utc_now_iso(),
        validation=validation,
    )
    manifest_path = output_dir / "MANIFEST.yaml"
    atomic_write_text(
        manifest_path, yaml.safe_dump(manifest.model_dump(mode="json"), sort_keys=False)
    )
    OperationLog(paths).append(
        operation_type="context_compile",
        actor="system:context",
        targets=[str(paths.root), target],
        command="hive context compile",
        changed_files=[
            {"path": str(pack_path.relative_to(paths.root))},
            {"path": str(manifest_path.relative_to(paths.root))},
        ],
        changed_records=[{"id": manifest.id, "type": "context_pack"}],
        rollback={"supported": False, "strategy": "regenerate_context_pack"},
    )
    return pack_path, manifest_path


def context_impact(root: Path, target: str) -> dict[str, Any]:
    paths = WorkspacePaths(root.resolve())
    paths.require_workspace()
    return {"ok": True, **MemoryGraph(paths.root).impact(target).as_dict()}


def invalidate_context(
    root: Path,
    target: str,
    *,
    reason: str,
    actor: str = "system:context",
    respect_policy: bool = True,
) -> dict[str, Any]:
    paths = WorkspacePaths(root.resolve())
    paths.require_workspace()
    impact = MemoryGraph(paths.root).impact(target)
    decision = context_invalidation_decision(
        paths,
        target=target,
        reason=reason,
        respect_policy=respect_policy,
    )
    invalidation_id = new_id("ctxinv")
    record = {
        "id": invalidation_id,
        "target": target,
        "reason": reason,
        "created_at": utc_now_iso(),
        "severity": "normal",
        "affected_context_packs": impact.context_packs,
        "affected_targets": impact.affected_targets,
        "status": "open" if decision["emit_dirty_marker"] else "observed",
        "policy_mode": decision["mode"],
        "policy_decision": decision["decision"],
    }
    path = paths.context_dirty / f"{invalidation_id}.yaml"
    changed_files: list[dict[str, Any]] = []
    if decision["emit_dirty_marker"]:
        atomic_write_text(path, yaml.safe_dump(record, sort_keys=False))
        changed_files.append({"path": str(path.relative_to(paths.root))})
    operation = OperationLog(paths).append(
        operation_type="context_invalidate",
        actor=actor,
        targets=[str(paths.root), target, *impact.affected_targets],
        command="hive context invalidate",
        changed_files=changed_files,
        changed_records=[
            {"id": invalidation_id, "type": "context_invalidation", "status": record["status"]}
        ],
        rollback={
            "supported": bool(changed_files),
            "strategy": "close_dirty_marker" if changed_files else "report_only",
        },
    )
    return {
        "ok": True,
        "invalidation": record if changed_files else None,
        "observation": record,
        "impact": impact.as_dict(),
        "operation": operation.id,
        "policy": decision,
    }
