"""Validation guardrails for memory and generated artifacts.

Module guide:
- `validate_memory_guardrails` checks workspace memory write safety.
- `validate_generated_artifact` verifies generated artifact metadata expectations.
- `dirty_markers_for_target` and `assert_context_fresh` enforce context freshness.

Maintenance: update this guide when adding public functions/classes to this module.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .errors import WorkspaceError
from .models import ValidationReport
from .paths import WorkspacePaths

CONTROLLED_SEGMENTS = {"published", "reviewed", "CURRENT.md"}
SHARED_AUTHORITIES = {"reviewed", "published"}


def is_controlled_memory_path(path: Path) -> bool:
    parts = set(path.parts)
    return bool(parts & CONTROLLED_SEGMENTS)


def validate_memory_guardrails(
    *,
    path: Path,
    data: dict[str, Any],
    body: str,
    report: ValidationReport,
) -> None:
    authority = str(data.get("authority", ""))
    status = str(data.get("status", "active"))
    if authority in SHARED_AUTHORITIES:
        if not data.get("source_refs"):
            report.add_error(
                "guardrail.source_refs_required",
                "Reviewed/published shared memory requires source_refs",
                str(path),
            )
        review = data.get("review") or {}
        if not isinstance(review, dict) or not review.get("reviewer") or not review.get("decision"):
            report.add_error(
                "guardrail.review_required",
                "Reviewed/published shared memory requires review metadata",
                str(path),
            )
        if not data.get("promotion"):
            report.add_error(
                "guardrail.promotion_required",
                "Reviewed/published shared memory requires promotion metadata",
                str(path),
            )
    if status == "archived" and "final_compaction" not in data and "archive_deferral" not in data:
        report.add_error(
            "guardrail.archive_requires_compaction",
            "Archive records require final_compaction or archive_deferral metadata",
            str(path),
        )
    if "/published/" in str(path).replace("\\", "/") and authority != "published":
        report.add_error(
            "guardrail.published_path_authority_mismatch",
            "Records under published/ must use authority=published",
            str(path),
        )
    if authority == "published" and "status: candidate" in body:
        report.add_warning(
            "guardrail.body_mentions_candidate",
            "Published record body still mentions candidate status",
            str(path),
        )


def validate_generated_artifact(path: Path, report: ValidationReport) -> None:
    if path.name == "PACK.md":
        text = path.read_text(encoding="utf-8", errors="ignore")
        if "Generated by Hive Synapse" not in text:
            report.add_error(
                "generated.hand_edit_marker_missing",
                "Generated context pack is missing generated artifact marker",
                str(path),
            )


def dirty_markers_for_target(paths: WorkspacePaths, target: str) -> list[Path]:
    markers: list[Path] = []
    if not paths.context_dirty.exists():
        return markers
    for path in sorted(paths.context_dirty.glob("*.yaml")):
        text = path.read_text(encoding="utf-8", errors="ignore")
        if f"target: {target}" in text or f'"target": "{target}"' in text:
            markers.append(path)
            continue
        if target in text and "affected_targets" in text:
            markers.append(path)
    return markers


def assert_context_fresh(paths: WorkspacePaths, target: str) -> None:
    markers = dirty_markers_for_target(paths, target)
    if markers:
        names = ", ".join(path.name for path in markers)
        raise WorkspaceError(f"Context for {target} is stale; dirty markers: {names}")
