"""Generated session and agent-instruction prompt definitions.

Module guide:
- `SESSION_OUTBOX_README_PROMPT` and `SESSION_BOOTSTRAP_PROMPT` guide sessions.
- `SESSION_SOUL_PROMPT`, `SESSION_USER_PROMPT`, `OPENCLAW_TOOLS_PROMPT`, and
  `SIGNIN_BOOTSTRAP_PROMPT` render generated agent-facing files.

Maintenance: update this guide when adding public prompt specs to this module.
"""

from __future__ import annotations

from .types import TextPromptSpec

SESSION_OUTBOX_README_PROMPT = TextPromptSpec(
    id="session_outbox_readme",
    version="v1",
    purpose="Tell an executing agent how to emit structured session memory deltas.",
    template="""# Hive Session Outbox

Write durable session memory here before running `hive session finish`.

Preferred file: `memory-delta.jsonl`, one JSON object per line.

Required fields per object:

- `type`: observation, decision, procedure, task, question, artifact, or summary.
- `summary`: concise durable statement.
- `body`: optional supporting detail.
- `target_scope`: one of private, node_candidate, edge_candidate, org_candidate.

Optional fields:

- `target`: defaults to `{actor_id}` for private memory and `{target}` for node candidates.
- `confidence`: number from 0.0 to 1.0.
- `source_refs`: list of source locators.
- `tags`: list of topic tags.

Example:

```json
{{"type":"decision","summary":"Use generated mounts for Codex sessions.","body":"AGENTS.md is generated and read-only; session memory is written to .hive/outbox.","target_scope":"node_candidate","target":"{target}","confidence":0.9,"tags":["session","codex"]}}
```

If there is nothing durable to save, write `no-memory-delta.md` with a short explanation.

Session: `{session_id}`
Actor: `{actor_id}`
""",
    safety_notes="Directs agents to summarize durable memory rather than persist raw transcripts.",
)

SESSION_BOOTSTRAP_PROMPT = TextPromptSpec(
    id="session_bootstrap",
    version="v1",
    purpose="Bootstrap harness agents inside a materialized Hive session mount.",
    template="""# {title}

This file is generated by `hive session start`. Treat it as read-only session bootstrap, not canonical memory.

## Required Startup Load

Read these files before doing task work:

1. `{context_rel}/SOUL.md`
2. `{context_rel}/CONTEXT.md`
3. `{context_rel}/USER.md`
4. `{context_rel}/MEMORY.md`
5. `{context_rel}/SCOPE.yaml`
6. `{context_rel}/manifest.yaml`

## Active Hive Identity

- Actor: `{actor}`
- Effective node: `{effective_node}`
- Role: `{role}`
- Sign-in: `{signin_id}`
- Personal memory home: `{personal_memory_home}`

## Memory Rules

- Do not edit this file or files under `{context_rel}/`; they are generated snapshots.
- Write durable private or candidate memory to `{outbox_rel}/memory-delta.jsonl`.
- Do not write parent, department, organization, or edge memory directly.
- Use `target_scope=private` for actor-private learnings.
- Use `target_scope=node_candidate` for reusable team or department knowledge.
- Use `target_scope=org_candidate` only for high-confidence organization-wide knowledge.
- Avoid raw chat logs, private reasoning, and transient task details.

## Finish Protocol

Before ending the session, write one JSON object per durable memory item to `{outbox_rel}/memory-delta.jsonl`.
Then run `hive session finish` on this mount so Hive can collect, summarize, and route memory through governed workflows.
""",
    safety_notes="Keeps generated bootstrap read-only and routes writes through the outbox.",
)

SESSION_SOUL_PROMPT = TextPromptSpec(
    id="session_soul",
    version="v1",
    purpose="Render generated identity and stance for a session context bundle.",
    template="""# SOUL

Generated identity and operating stance for this session.

- Actor: `{actor}`
- Role: `{role}`
- Effective node: `{effective_node}`
- Purpose: {purpose}

Follow the mission, tone, principles, and goals embedded in `CONTEXT.md`. If durable identity or operating principles should change, update the relevant Hive charter rather than editing generated session files.
""",
    safety_notes="Identity changes are directed to charters, not generated session files.",
)

SESSION_USER_PROMPT = TextPromptSpec(
    id="session_user",
    version="v1",
    purpose="Render session-specific working instructions for a context bundle.",
    template="""# USER

Session-specific working instructions.

- Adapter: `{adapter}`
- Sign-in: `{signin_id}`
- Instance: `{instance}`
- Purpose: {purpose}

Use the context snapshot for this run. If context appears stale, stop and ask for or run `hive actor refresh {signin_id}` before relying on older facts.
""",
    safety_notes="Encourages context refresh rather than stale-memory reliance.",
)

OPENCLAW_TOOLS_PROMPT = TextPromptSpec(
    id="openclaw_tools",
    version="v1",
    purpose="Render OpenClaw tool-use guidance for a Hive session mount.",
    template=(
        "# TOOLS\n\n"
        "Use the `hive` CLI for session finish, imports, proposals, compaction, "
        "validation, and audit.\n"
    ),
    safety_notes="Keeps OpenClaw writes routed through Hive CLI workflows.",
)

SIGNIN_BOOTSTRAP_PROMPT = TextPromptSpec(
    id="actor_signin_bootstrap",
    version="v1",
    purpose="Render direct actor sign-in instructions when no session mount is used.",
    template="""# Hive Synapse Sign-In: {signin_id}

Actor: `{actor}`
Effective node: `{effective_node}`
Role: `{role}`
Personal memory home: `{personal_memory_home}`

## Required Startup Load

Load context pack: `{context_pack}`
Read manifest: `{manifest}`

## Operating Boundary

- Treat agent-private memory as local working state.
- Treat Hive node, edge, and org memory as shared organizational context.
- Submit reusable findings through imports, candidates, and promotion rather than directly editing parent memory.
- Refresh this sign-in before acting if context dirty markers or upstream changes exist.
""",
    safety_notes="Direct sign-in mode still forbids direct parent/shared memory writes.",
)
